### ISSUE TITLE
"Linjan vetäjä" role cannot delete forum area

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2388]
Linjan vetäjä role can on edit and create forum areas but delete icon is missing as well as functionality.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1126

#### SH
Riikka Lehtonen

**Comment by pkukkon** [comment]
Removing forum areas is intentionally limited to administrators only. Needs grooming to determine if this functionality should be available to a wider audience.

One viable solution might be to allow removing those forum areas that the user himself/herself has created?

Then again, if this isn't really a widespread problem but a single incident, permissions should be kept as-is (i.e. only an administrator can remove a forum area) to limit the chance of accidents.

**Comment by pkukkon** [comment]
Also, it should be noted that, at the moment, removing a forum area has no confirmation dialog whatsoever and that even if forum areas have support for archiving (soft delete), a removed forum area is deleted permanently.

**Comment by pkukkon** [comment]
On the plus side, the application only allows removing empty forum areas.

Unfortunately, if you remove all threads from a forum area, those threads are actually archived, which in turn prevents the seemingly empty forum area to be removed due to an internal error :D

All in all, the current implementation is woefully broken in several ways.
