### ISSUE TITLE
data.fieldAnswers is undefined

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#245]
If there's any submitted exercises, the following error pops up when returning to the material page 

Vastausten lataamisessa tapahtui virhe: error
HTML-sivun lukemisessa tapahtui virhe: TypeError: data.fieldAnswers is undefined

Also seen in the wild:

HTML-sivun lukemisessa tapahtui virhe: TypeError: Cannot read property '4638..muikku-field-Wl21zccbJ9zrLNVtT7cibZWR' of undefined

**Comment by pkukkon** [comment]
The first one (data.fieldAnswers is undefined) was (potentially) fixed in commit becb46149de7e56a13f77b9d405b70f1baa74a3b. Material loader was always expecting fieldAnswers to be present whereas we have situations where the loading of answers is deliberately skipped. Thus, the fix was to simply check whether fieldAnswers was present before accessing it.

Leaving this open as it should be confirmed that the field answers are loaded or left unloaded depending on each use case. Also, the field property error has not been investigated yet.
