### ISSUE TITLE
Saved checkbox answers don't show up

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#293]

**Comment by pkukkon** [comment]
The code didn't account for the fact that a QuerySelectField can turn into a QueryMultiSelectField (and vice versa) simply by changing its type in the field properties dialog.

A refined way to handle this would be to refactor the code so that we only have QuerySelectField which can have multiple options as answers. However, the amount of work required for that is so big that it has been filed as its own issue (#305 Select fields need refactoring).

As for now, this has been fixed so that when a select field switches between single-select and multi-select, the old field is removed and a new field is created.
