### ISSUE TITLE
Fixes to StartUp-Muikku 

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3247]
StartUp-lukion korjauslista. Jos graffasta tai muusta kysyttävää, voi olla yhteydessä Jyri Öhman (jyri@kinda.fi):

1) Body-tekstin pistekokoa voisi nostaa 18:aan.

2) Footerille taustaväriksi #eaeaea. Trouble with Muikku -tekstiä ei saa palstoituksen vuoksi ilmeisesti sivun keskelle, joten sen voisi tasata palstan oikeaan reunaan ja antaa ylä- ja alapaddingia vaikka 5px.

3) Kursiivit näyttävät nyt faux italicilta – olihan Google Fontsista otettu käyttöön kaikki neljä leikkausta?

4) Kielivalikon ja loggautuneen käyttäjän fonttikooksi 15px.

5) Väripaletin voisi rajoittaa violettiin ja harmaisiin. Eli esimerkiksi profiilisivulta punaiset ja siniset sävyt violeteiksi (ja tekstit harmaiksi). Sopiva nappulatyyli näkyi asseteissa (jpg-liite, psd: )

6) Course pickerissä vaaleansininen taustaväri harmaaksi: #eaeaea. Materiaalisivulta saman taustavärin voisi poistaa.

7) Ikonien viivanpaksuus on liian ohut. Ovatko ikonit svg-kuvia? Voinko auttaa jotenkin tekemään niistä oikean paksuiset? Puuttuvia ikoneita siis logout ja profiili – oliko muita? Voimme tehdä noista sitten samaan tapaan uudet ikonit.

8) .workspace-teachers-empty -elementin vasen ja oikea padding pois, tekstin tasaus vasempaan laitaan.

9) Materiaalisivulla Table of Contentsin ja progressin tulisi olla tasattuna samaan kohtaan y-akselilla sivunavigaation kanssa.

10) Discussions-sivulla h3 näyttää väärältä. Käytetään otsikoita aina "isoilla kirjaimilla”, pääsääntöisesti aina brändiväri violetilla eikä koskaan italicilla.

11) Responsiivisuus ei toimi pienissä koissa. Koko navigaation voisi pienemmillä näyttökoilla tiputtaa hampurilaisikonin taakse ja laittaa UP-logon aina vasempaan yläkulmaan. Mobiilikoossa muuttuu turhaan sivun taustaväri ja navigaatiolle tulee pudotusvarjo – nämä pois.

Lisäksi:

12) Kurssin materiaalien sivu jotenkin rikki.

13)  Kirjautumissivulla mobiilileiskassa häviää Startup-lukion logo ja tilalle ilmestyy varjotettu vasemman yläkulman Muikku-logo.

**Comment by jjlankinen** [comment]
#### Done: 
- 1
- 2
- 3
- 4
- 6
- 9
- 10 (.di-message-title elements styling was changed as assumed this was the problem)
- 12 (possibly fixed maybe, as it was broken in someway?)

#### Partly done: 
- 5 (colors for buttons are changed, text is not changed to grayish as there seem to be mixture of purple and gray text in provided assets so itäs imposible to know when to you gray or purple for description texts ie. coursepicker and workspace differs from each other regarding description texts)

#### To do: 
- 7 (icon set is missing json file from cdn so it's not possible to out source icon fixing to designer as requested).
- Lots of wrong fonts in different elements as many buttons have Gentium Basic instead of Axis. This has to be specified better when to use Axis and when to use Gentium Basic. Same specification need goes for button and text colors and fonts  that is used in descriptions, labels, paragrahps etc. Only specifying paragraphs and one type of button covers only about 20% of text styling used in Muikku.
