### ISSUE TITLE
Startup High School: Evaluation request is missing

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3283]
As a student I would like send an evaluation request to teacher.

**Comment by pkukkon** [comment]
Fix pushed to branch #3110 but there are multiple issues:

- Evaluation button is visible in mobile view but was commented out in desktop view. Why?
- In both modes, the evaluation button is still blue, i.e. has not been given a new coat of paint.
- The Request Evaluation dialog is blue as well, i.e. has not been given a new coat of paint.
- Requesting evaluation failed due to bug #3168 which exists in devel but not branch #3110.
- Devel should be merged into branch #3110 which most likely causes plenty of new work.

All in all, branch #3110 is woefully out of date but at least it is now possible to request an evaluation, even if the UI looks awkward.
