### ISSUE TITLE
Cyrillic characters support

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3866]
Check if Muikku supports cyrillic characters.

**Comment by RazgrizX** [comment]
Checked:
Muikku-
Main page, most recent;
Main page, workspaces;
Main page, messages;
Main page, announcements;
Course picker, curriculum;
Course picker, course;
Course picker, search;
Communicator, message new message;
Communicator, message sent;
Communicator, message received;
Communicator, message unread;
Communicator, auto generated message received;
Discussion. new message;
Discussion, all messages;
Discussion, message;
Discussion, reply;
Guider, workspaces filter;
Guider, flags filter;
Guider, user profile, add flag;
Guider, user profile, flags;
Evaluation, evaluation request course name;
Evaluation Assignment, name and text;
Evaluation Assignment, AAAA in english letters in answer differs from АААА in russian (which is fine);
Evaluation Assignment, evaluate workspace feedback;
Evaluation Assignment, evaluate assignment feedback;
Announcer, new announcement, header,text and target group;
Announcer, announcements;
Announcer, edit announcements;
User Profile, changed user and password to cyrrilic letters (Might need to be limited!)

Pyramus-
Created module,
Created course,
Created component,
Created curriculum,

Conclusion:
"Open Sans",Arial,sans-serif used in Muikku has 300 as a minimum weight for Latin and 500 as a minimum weight for Cyrillic. Since 300 is used everywhere this issue makes it impossible to use. Otherwise, the design is ruined. It is strange since according to this: https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans:300i
everything should be fine. (Issue #3886 created)
"trebuchet ms", verdana, sans-serif used in Pyramus has 500 as a minimum weight for both Latin and Cyrillic letters. Works fine.
The Cyrillic letters work fine, except for font-weight, wherever I checked. 
I have also changed login and password to cyrrilic letters. This might need to be limited.
