### ISSUE TITLE
Update contact information dialog is missing

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4031]
Update contact information dialog seems to be missing in redesign version.

Dialog is activated by request for every student.

Dialog will popup automatically when set active.

**Comment by onzag** [comment]
Ok the push was made to the main branch.

At last moment I added the FORCE_OPEN constant to the check-contact-info-dialog.tsx file, search for it, you can use that variable and set it to true to always force open the dialog wheter it has been updated or not, so you can style it; note that it requires that the student has an address set otherwise it won't work.

It needs some styling but it's functionally fine.
