### ISSUE TITLE
Image details loading does not account if href is set or not

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4518]
when setting image details without href-links the are still loaded as link tags.

There needs to be check whether every data source has link or not and handled accordingly.

Also license data does not get loaded at all

**Comment by onzag** [comment]
While the whole href cannot be unset, I changed (as what I understood) how it is displayed in the copyright information.

There's an issue within the ckeditor that it doesn't load the images because it depends in jquery, I spend some time trying to find a fix but couln't figure out, it is some dead code from the lazyload that cannot quite be removed, lazyload interferes with the new tech, but the plugin seemed to leak to the old tech.

I assume the plugin has to be rewritten or modified, and I honestly don't know how the field plugins were written, so I am attempting to see how can this be fixed.
