### ISSUE TITLE
Exercise answer revealing not working properly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4547]
Some taskfields does not work properly if page i set to reveal answers only by request or never to reveal them.

Submit button does not change and some taskfields still shows correct answers by default.

**Comment by onzag** [comment]
I believe this is fixed, the logic was incomplete in each field as how it was handling it; it was ignoring the flag that tell it not to display correct answers and using the one that told it to check for correct answers (but not to display them).

Notice however that the check correct answers flag makes it so that "Correct Answers 2/3" shows at the bottom, this can be disabled if required, but I believe it worked like that in production (did it?).
