### ISSUE TITLE
Incomplete assignment message enhancement

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#4589]
Teacher says:

> kolme opiskelijaa on nyt maininnut siitä, että täydennyspyyntöjen tekstit katoavat, kun tehtävää alkaa muokkaamaan tai että täydennyspyyntöjen tekstit eivät näy ollenkaan.

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2788

The problem can be seen on refresh after the student cancels the assignment.

This calls for 2 things, second is optional and maybe should be discussed :

1. Show the "incomplete"-message until the assignment has a true evaluation
2. Show the "incomplete"- message all the time under the assignment. The click is needless.

**Comment by pkukkon** [comment]
Affects both assignment evaluations and supplementation requests. They are shown to student at first but if the student then withdraws their answer and reloads the page, that information disappears since the assignment has returned to non-submitted state.

Should probably be fixed so that if an assignment has ever been evaluated or marked as needing supplementation (whichever is newer), that information is always shown, even if the student withdraws their previous answer or makes changes and re-submits the assignment.

Note that once an assignment has been given a passing grade, it can no longer be withdrawn or re-submitted.
