### ISSUE TITLE
License needs separate text and link selections

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4834]
License that is used in workspaces and material pages currently has **Text or link** selection but that is problematic as license can be only text without any reference to any website when link should be displayed always as a hyperlink.

We need to be able to add text license that has no reference to anywhere and we should be able to set license as a link to the specific website and behave as a normal hyperlink.

Currently every license is handled as hyperlink and inputting plain text as a license looks a bit stupid.

Child of #4087

**Comment by onzag** [comment]
This can't be implemented consistently as there's no difference between link and text from the data perspective.

Previously it was implemented in an inconsistent way, the problem is that unlike Commons license, a random link and text isn't consistent, and because due to react, reactive nature, it doesn't make a difference between loading and user input which would cause text and link to toggle around as you type.

**Comment by onzag** [comment]
When loading the license, it just checks for whether it is a link and displays it as a link, so there's no problem for students, but when writting the value, checking for that would just cause random toggling, as you type your link is invalid, which is text.

**Comment by jjlankinen** [comment]
It's enough if we check whether text/link value contains http and render it accordingly.
