### ISSUE TITLE
MathJax inside CKEditor don't support Scandinavian letters properly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4955]
It seems that when adding Scandinavian letters within the MathJax formulas they don't obey the font formatting properly. Formulae is rendered italic but Scandinavian letters are not.

**Comment by onzag** [comment]
I poked with this issue several times but I couldn't find a solution, this issue exists within a plugin inside of the ckeditor itself because the scandinavian letters are not quite supported by mathjax itself.

This is not exclusive to the ckeditor itself, this is an entire thing with mathjax and in fact the whole TeX environment.
