### ISSUE TITLE
Some page attachments briefly cause 404 when page is loaded

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#4991]
Steps to reproduce:

1) Add an .mp3 file as an attachment to a page
2) Add an audio field to the page, source being just the .mp3 filename
3) Publish
4) Load the page with console open
5) Log shows a couple of 404s about the audio file being loaded from the workspace root

Since the rendered audio field has the correct file path (materials/section/page/audio.mp3), could it be that the audio tag is appended to DOM as-is (browser immediately tries to load it) and the baseUrl is appended to the source a bit later, which then makes it work properly?

**Comment by onzag** [comment]
This was already checked before and there was simply no solution as this is caused immediately because of the parsing of the HTML, without the processing, so it's a bug in the chromium engine itself; not a deadly bug, but a bug nonetheless.

I think the issue should be closed since it has no effect overall over the user expectations.
